/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AlleyRouteImport } from './routes/alley'
import { Route as CatteryRouteImport } from './routes/cattery'
import { Route as DocsRouteImport } from './routes/docs'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AlleyRoute = AlleyRouteImport.update({
  id: '/alley',
  path: '/alley',
  getParentRoute: () => rootRouteImport,
} as any)
const CatteryRoute = CatteryRouteImport.update({
  id: '/cattery',
  path: '/cattery',
  getParentRoute: () => rootRouteImport,
} as any)
const DocsRoute = DocsRouteImport.update({
  id: '/docs',
  path: '/docs',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/alley': typeof AlleyRoute
  '/cattery': typeof CatteryRoute
  '/docs': typeof DocsRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/alley': typeof AlleyRoute
  '/cattery': typeof CatteryRoute
  '/docs': typeof DocsRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/alley': typeof AlleyRoute
  '/cattery': typeof CatteryRoute
  '/docs': typeof DocsRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/alley' | '/cattery' | '/docs'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/alley' | '/cattery' | '/docs'
  id: '__root__' | '/' | '/alley' | '/cattery' | '/docs'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AlleyRoute: typeof AlleyRoute
  CatteryRoute: typeof CatteryRoute
  DocsRoute: typeof DocsRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/alley': {
      id: '/alley'
      path: '/alley'
      fullPath: '/alley'
      preLoaderRoute: typeof AlleyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cattery': {
      id: '/cattery'
      path: '/cattery'
      fullPath: '/cattery'
      preLoaderRoute: typeof CatteryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/docs': {
      id: '/docs'
      path: '/docs'
      fullPath: '/docs'
      preLoaderRoute: typeof DocsRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AlleyRoute: AlleyRoute,
  CatteryRoute: CatteryRoute,
  DocsRoute: DocsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
